### ISSUE TITLE
reliability index for better results

### ISSUE THREAD

**Issue by Nautic** [tomayac/wikipedia-tools-for-google-spreadsheets#11] opened 2016-10-13 08:08 UTC
In my use case (Terms connecting to WP-articles), the result is about 30% good links.
For filtering the wrong ones, it would be great to get a "reliability index" :-)

(1. handy approved accordance of Term and WP-article)
2. Term and Lemma identical
3. Term and section title identical
4. all words in Term found in Lemma
5. all words in Term found in section title
6. Term found as string in article text

**Comment by tomayac** [comment] 2016-10-14 07:22
@Nautic, what you are describing here is essentially the challenge of entity linking, *i.e.*, going from an ambiguous string like "Jaguar" to the clearly and unambiguously defined thing [Jaguar](https://en.wikipedia.org/wiki/Jaguar), or, wait, rather [Jaguar](https://en.wikipedia.org/wiki/Jaguar_(disambiguation))?! As you can see from this trivial example, the problem is hard, especially when there is no context. The Wikipedia Search API returns the most probable (list of) thing(s) for string, which is what I am exposing in the add-on. Everything else would be far beyond the scope of the objectives of the tool, which is why I hope you understand if I close the issue. Hope you still find the add-on useful!

**Closed by tomayac** 2016-10-14 07:22 UTC

**Comment by Nautic** [comment] 2016-10-14 10:23
Hi Tom, in the 'Jaguar' case: 
I suggest an additional disambiguation-index.

If the tool finds a disambiguation page, 
you could set the disambiguation-index to something like: 
x =' [Disambiguation Type I](https://de.wikipedia.org/wiki/Wikipedia:Begriffskl%C3%A4rung#Die_Begriffskl.C3.A4rungsseite_.28BKS.29)
y = [Disambiguation Type II](https://de.wikipedia.org/wiki/Wikipedia:Begriffskl%C3%A4rung#BKL_II_.E2.80.93_Das_Stichwort_f.C3.BChrt_auf_den_gel.C3.A4ufigsten_Sachartikel)
z = [Disambiguation Type III](https://de.wikipedia.org/wiki/Wikipedia:Begriffskl%C3%A4rung#BKL_III_.E2.80.93_Das_Stichwort_f.C3.BChrt_auf_eine_Weiterleitung)

So together with the reliability-index, the user would have a helpful information about 
the quality of each result :-)

Aim is to get a basis for an ABC-decision:
- which results can we use immediately
- which can we improve in an easy way by hand 
- which should we temporarily throw away 

Bests, Markus
